// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cricket_data.data;

#nullable disable

namespace cricket_data.Migrations
{
    [DbContext(typeof(CricketDataDb))]
    [Migration("20240904085106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cricket_data.data.BowlingInnings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Economy")
                        .HasColumnType("real");

                    b.Property<int?>("GroundId")
                        .HasColumnType("int");

                    b.Property<string>("GroundName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Innings")
                        .HasColumnType("int");

                    b.Property<int>("Maidens")
                        .HasColumnType("int");

                    b.Property<string>("Opposition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Overs")
                        .HasColumnType("real");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Runs")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TestNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wickets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroundId");

                    b.HasIndex("PlayerId");

                    b.ToTable("BowlingInnings");
                });

            modelBuilder.Entity("cricket_data.data.Ground", b =>
                {
                    b.Property<int>("GroundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroundId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("GroundId");

                    b.ToTable("Grounds");
                });

            modelBuilder.Entity("cricket_data.data.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("CricInfoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("cricket_data.data.BowlingInnings", b =>
                {
                    b.HasOne("cricket_data.data.Ground", "Ground")
                        .WithMany("BowlerInnings")
                        .HasForeignKey("GroundId");

                    b.HasOne("cricket_data.data.Player", "Player")
                        .WithMany("BowlerInnings")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Ground");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("cricket_data.data.Ground", b =>
                {
                    b.Navigation("BowlerInnings");
                });

            modelBuilder.Entity("cricket_data.data.Player", b =>
                {
                    b.Navigation("BowlerInnings");
                });
#pragma warning restore 612, 618
        }
    }
}
